# Generated by Django 3.0.2 on 2020-03-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('RegisteredDate', models.DateTimeField()),
                ('Condition', models.CharField(choices=[('poor', 'POOR'), ('good', 'GOOD'), ('new', 'NEW')], default='good', max_length=5)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
    ]
