# Generated by Django 3.0.2 on 2020-03-25 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brief', models.TextField()),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('MinimumPrice', models.FloatField()),
                ('CreatedByUsername', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('ItemCondition', models.CharField(choices=[('poor', 'POOR'), ('good', 'GOOD'), ('new', 'NEW')], default='good', max_length=5)),
                ('FirstRegDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlacedDate', models.DateTimeField()),
                ('BidPrice', models.FloatField()),
                ('Auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actions.Auction')),
                ('PlacedByUsername', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Item'),
        ),
        migrations.AddField(
            model_name='auction',
            name='WinnerBid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.Bid'),
        ),
    ]
