# Generated by Django 3.0.2 on 2020-03-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_remove_auction_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemCode',
            field=models.CharField(max_length=10),
        ),
    ]
