# Generated by Django 3.0.2 on 2020-03-08 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0002_remove_item_registereddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('MinimumPrice', models.FloatField()),
                ('CreatedByUsername', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ItemCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actions.Item')),
            ],
        ),
    ]
