# Generated by Django 3.0.2 on 2020-03-18 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='Brief',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='FirstRegDate',
            field=models.DateTimeField(default=datetime.date(2020, 3, 18)),
            preserve_default=False,
        ),
    ]
