# Generated by Django 3.0.2 on 2020-03-25 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20200325_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='Item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='actions.Item'),
            preserve_default=False,
        ),
    ]
