# Generated by Django 3.0.2 on 2020-03-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_auto_20200318_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Condition',
        ),
        migrations.AddField(
            model_name='auction',
            name='ItemCondition',
            field=models.CharField(choices=[('poor', 'POOR'), ('good', 'GOOD'), ('new', 'NEW')], default='good', max_length=5),
        ),
    ]
