# Generated by Django 3.0.2 on 2020-03-19 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_auto_20200318_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='ItemCode',
            new_name='Item',
        ),
    ]
