# Generated by Django 3.0.2 on 2020-04-02 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_auto_20200326_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='Brief',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='WinnerBid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='actions.Bid'),
        ),
    ]
