# Generated by Django 3.0.2 on 2020-04-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_auto_20200402_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='PlacedByUsername',
            new_name='PlacedByUser',
        ),
    ]
