# Generated by Django 3.0.2 on 2020-03-25 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_auto_20200325_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='Auction1',
            new_name='Auction',
        ),
        migrations.AddField(
            model_name='bid',
            name='PlacedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 0, 45, 50, 14777)),
            preserve_default=False,
        ),
    ]
