# Generated by Django 3.0.2 on 2020-04-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_auto_20200402_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='CreatedByUsername',
        ),
    ]
